"""Add routes and visibility

Revision ID: f4bfe6084517
Revises: 2e63d9f9bd94
Create Date: 2025-12-23 16:21:33.520831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4bfe6084517'
down_revision: Union[str, Sequence[str], None] = '2e63d9f9bd94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type manually for PostgreSQL
    route_visibility = sa.Enum('ALWAYS', 'START_ONLY', 'SECRET', name='routevisibility')
    route_visibility.create(op.get_bind())

    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gpx_data', sa.Text(), nullable=False),
    sa.Column('distance_meters', sa.Numeric(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_created_by_user_id'), 'routes', ['created_by_user_id'], unique=False)
    op.add_column('rides', sa.Column('route_id', sa.Integer(), nullable=True))
    
    # 1. Add visibility column as nullable
    op.add_column('rides', sa.Column('visibility', route_visibility, nullable=True))
    
    # 2. Set default value for existing rows
    op.execute("UPDATE rides SET visibility = 'ALWAYS'")
    
    # 3. Make it NOT NULL
    op.alter_column('rides', 'visibility', nullable=False)

    op.alter_column('rides', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_rides_start_time'), 'rides', ['start_time'], unique=False)
    op.drop_constraint(op.f('rides_created_by_user_id_fkey'), 'rides', type_='foreignkey')
    op.create_foreign_key(None, 'rides', 'users', ['created_by_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rides', 'routes', ['route_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.create_foreign_key(op.f('rides_created_by_user_id_fkey'), 'rides', 'users', ['created_by_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_rides_start_time'), table_name='rides')
    op.alter_column('rides', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('rides', 'visibility')
    
    # Drop the Enum type manually for PostgreSQL
    route_visibility = sa.Enum('ALWAYS', 'START_ONLY', 'SECRET', name='routevisibility')
    route_visibility.drop(op.get_bind())

    op.drop_column('rides', 'route_id')
    op.drop_index(op.f('ix_routes_created_by_user_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
